# Generated by Selenium IDE
import pytest
import time
import json
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestHogwartsWeb:

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_hogwarts(self):
        self.driver.get("https://ceshiren.com/")

        time.sleep(5)
        self.driver.set_window_size(2199, 1355)

        time.sleep(5)
        self.driver.find_element(By.XPATH, "//*[@title='测试答疑']").click()

        time.sleep(5)
        self.driver.close()
